### ISSUE TITLE
run the dependency parser on a file in CoNLL format

### ISSUE THREAD

**Issue by lavelli** [emorynlp/nlp4j-demo#2]
I have started using version 1.1.1 and managed to successfully train the dependency parser. However, when I try to run the decoder using the demo package I have some trouble.
I would like to directly run the dependency parser providing as input a file in CoNLL format.
In the previous release of nlp4j-demo there was the class DEPDecode that did this. In the new release it seems that a few changes were made that prevent the DEPDecode code from compiling successfully (and the new NLPDecoderDemo performs a different task). I fixed some of the issues changing a few paths but I cannot understand how to create an object TSVReader (I browsed the github repository but I was not able to find the relevant source code).
In attachment a zipfile with the current version of DEPDecode.java after my changes. When compiling it produces an error on line 62 "cannot find symbol TSVReader".

thanks

[DEPDecode.zip](https://github.com/emorynlp/nlp4j-demo/files/281039/DEPDecode.zip)

**Comment by jdchoi77** [comment]
I updated [DEPDecode](https://github.com/emorynlp/nlp4j-demo/blob/master/src/main/java/edu/emory/mathcs/nlp/demo/DEPDecode.java).  Please try out and let me know if you still cannot run.  Thanks.

best,

Jinho
